export type Vec={x:number;y:number};
export type Resource='fuel'|'oxidizer'|'metal'|'shells'|'minerals';
export type ComponentType='hull'|'engine'|'thruster'|'tank'|'cannon'|'ammo'|'scoop'|'factory'|'armor';
export type Component={id:string;type:ComponentType;pos:Vec;mass:number;integrity:number;resources?:Partial<Record<Resource,number>>;capacity?:Partial<Record<Resource,number>>;facing?:number;radius:number};
export type Link={id:string;type:'control'|'resource'|'structural'|'manufacturing';from:string;to:string;integrity:number;capacity:number};
export type Body={id:string;pos:Vec;vel:Vec;angle:number;angVel:number;mass:number;inertia:number;components:Component[];links:Link[]};
export type Parcel={id:string;kind:'gas'|'mineral'|'shell'|'asteroid';pos:Vec;vel:Vec;mass:number;radius:number;integrity:number};
export type Command={forward?:boolean;left?:boolean;right?:boolean;fire?:boolean;scoop?:boolean;repair?:boolean;manufacture?:boolean};
export type World={ship:Body;parcels:Parcel[];time:number;log:string[]};
const add=(a:Vec,b:Vec):Vec=>({x:a.x+b.x,y:a.y+b.y});
const sub=(a:Vec,b:Vec):Vec=>({x:a.x-b.x,y:a.y-b.y});
const mul=(a:Vec,s:number):Vec=>({x:a.x*s,y:a.y*s});
const len=(a:Vec)=>Math.hypot(a.x,a.y);
const rot=(v:Vec,a:number):Vec=>({x:v.x*Math.cos(a)-v.y*Math.sin(a),y:v.x*Math.sin(a)+v.y*Math.cos(a)});
const cross=(a:Vec,b:Vec)=>a.x*b.y-a.y*b.x;
export function recalc(body:Body){let m=0,cm={x:0,y:0};for(const c of body.components){const contents=Object.values(c.resources??{}).reduce((a,b)=>a+(b??0),0);const capFactor=Math.max(0,c.integrity);const mass=c.mass+contents;m+=mass;cm=add(cm,mul(c.pos,mass*capFactor));}cm=mul(cm,1/Math.max(0.0001,m));let inertia=0;for(const c of body.components){const contents=Object.values(c.resources??{}).reduce((a,b)=>a+(b??0),0);const mass=c.mass+contents;inertia+=mass*(c.radius*c.radius/2+len(sub(c.pos,cm))**2);}body.mass=m;body.inertia=inertia;return cm;}
export function basicShip():Body{const components:Component[]=[
{id:'hull',type:'hull',pos:{x:0,y:0},mass:12,integrity:1,radius:18},{id:'engine',type:'engine',pos:{x:-35,y:0},mass:5,integrity:1,facing:Math.PI,radius:10},
{id:'leftThruster',type:'thruster',pos:{x:10,y:-20},mass:2,integrity:1,facing:Math.PI/2,radius:6},{id:'rightThruster',type:'thruster',pos:{x:10,y:20},mass:2,integrity:1,facing:-Math.PI/2,radius:6},
{id:'fuel',type:'tank',pos:{x:-5,y:-12},mass:3,integrity:1,resources:{fuel:20},capacity:{fuel:20},radius:7},{id:'oxidizer',type:'tank',pos:{x:-5,y:12},mass:3,integrity:1,resources:{oxidizer:20},capacity:{oxidizer:20},radius:7},
{id:'metal',type:'tank',pos:{x:18,y:0},mass:3,integrity:1,resources:{metal:2,minerals:0},capacity:{metal:15,minerals:30},radius:8},{id:'ammo',type:'ammo',pos:{x:25,y:10},mass:2,integrity:1,resources:{shells:4},capacity:{shells:6},radius:6},
{id:'cannon',type:'cannon',pos:{x:35,y:0},mass:4,integrity:1,facing:0,radius:8},{id:'scoop',type:'scoop',pos:{x:25,y:-12},mass:2,integrity:1,radius:10},{id:'factory',type:'factory',pos:{x:8,y:10},mass:4,integrity:1,radius:8},{id:'armor',type:'armor',pos:{x:0,y:-25},mass:5,integrity:1,radius:18}];
const ids=components.map(c=>c.id); const links:Link[]=ids.filter(id=>id!=='hull').map((id,i)=>({id:'s'+i,type:'structural',from:'hull',to:id,integrity:1,capacity:12}));
links.push({id:'forward',type:'control',from:'hull',to:'engine',integrity:1,capacity:1},{id:'turnL',type:'control',from:'hull',to:'rightThruster',integrity:1,capacity:1},{id:'turnR',type:'control',from:'hull',to:'leftThruster',integrity:1,capacity:1});
for(const to of ['engine','leftThruster','rightThruster','cannon']) links.push({id:'fuel-'+to,type:'resource',from:'fuel',to,integrity:1,capacity:2},{id:'ox-'+to,type:'resource',from:'oxidizer',to,integrity:1,capacity:2});
links.push({id:'ammo-cannon',type:'resource',from:'ammo',to:'cannon',integrity:1,capacity:1},{id:'scoop-metal',type:'resource',from:'scoop',to:'metal',integrity:1,capacity:5},{id:'factory-metal',type:'manufacturing',from:'metal',to:'factory',integrity:1,capacity:1},{id:'factory-ammo',type:'manufacturing',from:'factory',to:'ammo',integrity:1,capacity:1});
const b={id:'ship',pos:{x:300,y:250},vel:{x:0,y:0},angle:0,angVel:0,mass:0,inertia:0,components,links};recalc(b);return b;}
function has(world:World,from:string,to:string,type:Link['type']){return world.ship.links.some(l=>l.from===from&&l.to===to&&l.type===type&&l.integrity>0.1)}
function drawRes(ship:Body,res:Resource,amount:number){const c=ship.components.find(c=>(c.resources?.[res]??0)>=amount); if(!c?.resources)return false; c.resources[res]=(c.resources[res]??0)-amount; return true;}
function impulse(ship:Body,at:Vec,force:Vec,dt:number){ship.vel=add(ship.vel,mul(force,dt/ship.mass)); ship.angVel+=cross(at,force)*dt/ship.inertia;}
export function step(world:World,cmd:Command,dt=.016){const ship=world.ship; const cm=recalc(ship); const fireThruster=(id:string,control:boolean)=>{const c=ship.components.find(c=>c.id===id); if(!c||!control||c.integrity<=0.1)return; if(!has(world,'fuel',id,'resource')||!has(world,'oxidizer',id,'resource')){world.log.push(`${id} missing reactants`);return} if(!drawRes(ship,'fuel',.02)||!drawRes(ship,'oxidizer',.02))return; const dir=rot({x:Math.cos(c.facing??0),y:Math.sin(c.facing??0)},ship.angle); const force=mul(dir,-220*c.integrity); impulse(ship,rot(sub(c.pos,cm),ship.angle),force,dt); world.parcels.push({id:crypto.randomUUID(),kind:'gas',pos:add(ship.pos,rot(c.pos,ship.angle)),vel:add(ship.vel,mul(dir,120)),mass:.04,radius:2,integrity:1});};
fireThruster('engine',!!cmd.forward); fireThruster('leftThruster',!!cmd.right); fireThruster('rightThruster',!!cmd.left);
if(cmd.fire&&has(world,'ammo','cannon','resource')&&drawRes(ship,'shells',1)){const c=ship.components.find(c=>c.id==='cannon')!; const dir=rot({x:1,y:0},ship.angle); const p=add(ship.pos,rot(c.pos,ship.angle)); world.parcels.push({id:crypto.randomUUID(),kind:'shell',pos:p,vel:add(ship.vel,mul(dir,180)),mass:1,radius:3,integrity:1}); impulse(ship,rot(sub(c.pos,cm),ship.angle),mul(dir,-180),dt); world.log.push('Cannon fired with physical recoil');}
if(cmd.manufacture){const metal=ship.components.find(c=>c.id==='metal')!;const ammo=ship.components.find(c=>c.id==='ammo')!; if((metal.resources?.metal??0)>=1&&(ammo.resources?.shells??0)<(ammo.capacity?.shells??0)){metal.resources!.metal!--; ammo.resources!.shells=(ammo.resources!.shells??0)+1; world.log.push('Nanofactory made one shell');}}
if(cmd.repair){const damaged=ship.components.find(c=>c.integrity<1); const metal=ship.components.find(c=>c.id==='metal')!; if(damaged&&(metal.resources?.metal??0)>.1){metal.resources!.metal!-=.1; damaged.integrity=Math.min(1,damaged.integrity+.05); world.log.push(`Repaired ${damaged.id}`);}}
for(const p of world.parcels){p.pos=add(p.pos,mul(p.vel,dt)); if(p.kind==='shell'){for(const a of world.parcels.filter(x=>x.kind==='asteroid'&&x!==p&&len(sub(x.pos,p.pos))<x.radius+p.radius)){a.integrity-=.5; p.integrity=0; if(a.integrity<=0){a.kind='mineral';a.radius=5;a.mass*=.8;a.integrity=1;world.log.push('Asteroid fragmented into collectible minerals');}}} if(cmd.scoop&&p.kind==='mineral'&&len(sub(p.pos,ship.pos))<45){const store=ship.components.find(c=>c.id==='metal')!; if((store.resources!.minerals??0)+p.mass<=(store.capacity!.minerals??0)){store.resources!.minerals=(store.resources!.minerals??0)+p.mass; ship.vel=mul(add(mul(ship.vel,ship.mass),mul(p.vel,p.mass)),1/(ship.mass+p.mass)); p.integrity=0; world.log.push('Scooped minerals with momentum transfer');}}}
world.parcels=world.parcels.filter(p=>p.integrity>0&&p.pos.x>-100&&p.pos.x<900&&p.pos.y>-100&&p.pos.y<700); ship.pos=add(ship.pos,mul(ship.vel,dt)); ship.angle+=ship.angVel*dt; world.time+=dt;}
export function createWorld():World{return{ship:basicShip(),parcels:[{id:'asteroid',kind:'asteroid',pos:{x:600,y:250},vel:{x:-5,y:0},mass:20,radius:25,integrity:1}],time:0,log:['Basic ship ready: thrust, torque, cannon, scoop, factory, repair.']}}
export function validateDesign(ship:Body){const errors:string[]=[];for(let i=0;i<ship.components.length;i++)for(let j=i+1;j<ship.components.length;j++)if(len(sub(ship.components[i].pos,ship.components[j].pos))<(ship.components[i].radius+ship.components[j].radius)*.35)errors.push(`${ship.components[i].id} overlaps ${ship.components[j].id}`);return{launchBlocked:errors.length>0,errors,warnings:ship.links.filter(l=>l.integrity<.5).map(l=>`${l.id} is fragile`)}}
